name: Bug Report
description: Found a bug? Awesome, tell us!
labels: ['bug', 'needs triage']
body:
    - type: textarea
      id: description
      attributes:
          label: Describe the bug
          description: What happened?
          placeholder: Describe the bug...
      validations:
          required: true
    - type: textarea
      id: reproduction
      attributes:
          label: Reproduction
          description: How can we recreate the bug to test it and patch it
          placeholder: How does it happen?...
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Logs
          description: Please copy and paste the errors from console
          render: bash
    - type: textarea
      id: system-info
      attributes:
          label: System Info
          description: Output of `npx envinfo --system --binaries --npmPackages jellycommands,discord.js` in the __same folder__ as your bot
          render: bash
          placeholder: System Information...
      validations:
          required: true
