name: "Feature Request"
description: Request a new feature in JellyCommands
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A detailed description of the feature would be awesome, but not required.
      placeholder: I want x because...
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Examples
      description: Some examples of where this feature can be seen in the wild.
      placeholder: Command handler x has this because y...
    validations:
      required: false
